from __future__ import annotations

from contextlib import suppress

from .booleans import (
    _boolean_union_many,
    _geometry_from_manifold,
    _manifold_from_geometry,
    boolean_difference,
    boolean_intersection,
    boolean_union,
    cut_opening_on_face,
    mesh_from_geometry,
    save_mesh_geometry,
)
from .brackets import ClevisBracketGeometry, PivotForkGeometry, TrunnionYokeGeometry
from .common import (
    WirePath,
    resample_side_sections,
    rounded_rect_profile,
    sample_arc_3d,
    sample_catmull_rom_spline_2d,
    sample_catmull_rom_spline_3d,
    sample_cubic_bezier_spline_2d,
    sample_cubic_bezier_spline_3d,
    split_superellipse_side_loft,
    superellipse_profile,
    superellipse_side_loft,
)
from .controls import BezelGeometry, KnobGeometry
from .fans import BlowerWheelGeometry, FanRotorGeometry
from .hinges import BarrelHingeGeometry, PianoHingeGeometry
from .panels import (
    LouverPanelGeometry,
    PerforatedPanelGeometry,
    SlotPatternPanelGeometry,
    VentGrilleGeometry,
)
from .primitives import (
    BoxGeometry,
    CapsuleGeometry,
    ConeGeometry,
    CylinderGeometry,
    DomeGeometry,
    ExtrudeGeometry,
    ExtrudeWithHolesGeometry,
    LatheGeometry,
    LoftGeometry,
    MeshGeometry,
    SphereGeometry,
    TorusGeometry,
)
from .specs import (
    BezelCutout,
    BezelEdgeFeature,
    BezelFace,
    BezelFlange,
    BezelMounts,
    BezelRecess,
    BezelVisor,
    BoltPattern,
    FanRotorBlade,
    FanRotorHub,
    FanRotorShroud,
    HingeHolePattern,
    HingePinStyle,
    KnobBore,
    KnobGrip,
    KnobIndicator,
    KnobRelief,
    KnobSkirt,
    KnobTopFeature,
    TireCarcass,
    TireGroove,
    TireShoulder,
    TireSidewall,
    TireTread,
    VentGrilleFrame,
    VentGrilleMounts,
    VentGrilleSlats,
    VentGrilleSleeve,
    WheelBore,
    WheelFace,
    WheelFlange,
    WheelHub,
    WheelRim,
    WheelSpokes,
)
from .sweeps import (
    ArcPipeGeometry,
    PipeGeometry,
    SweepGeometry,
    WirePolylineGeometry,
    sweep_profile_along_spline,
    tube_from_spline_points,
    tube_network_from_paths,
    wire_from_points,
)
from .wheels import TireGeometry, WheelGeometry

__all__ = [
    "ArcPipeGeometry",
    "BarrelHingeGeometry",
    "BezelCutout",
    "BezelEdgeFeature",
    "BezelFace",
    "BezelFlange",
    "BezelGeometry",
    "BezelMounts",
    "BezelRecess",
    "BezelVisor",
    "BlowerWheelGeometry",
    "BoltPattern",
    "BoxGeometry",
    "CapsuleGeometry",
    "ClevisBracketGeometry",
    "ConeGeometry",
    "CylinderGeometry",
    "DomeGeometry",
    "ExtrudeGeometry",
    "ExtrudeWithHolesGeometry",
    "FanRotorBlade",
    "FanRotorGeometry",
    "FanRotorHub",
    "FanRotorShroud",
    "HingeHolePattern",
    "HingePinStyle",
    "KnobBore",
    "KnobGeometry",
    "KnobGrip",
    "KnobIndicator",
    "KnobRelief",
    "KnobSkirt",
    "KnobTopFeature",
    "LatheGeometry",
    "LoftGeometry",
    "LouverPanelGeometry",
    "MeshGeometry",
    "PerforatedPanelGeometry",
    "PianoHingeGeometry",
    "PipeGeometry",
    "PivotForkGeometry",
    "SlotPatternPanelGeometry",
    "SphereGeometry",
    "SweepGeometry",
    "TireCarcass",
    "TireGeometry",
    "TireGroove",
    "TireShoulder",
    "TireSidewall",
    "TireTread",
    "TorusGeometry",
    "TrunnionYokeGeometry",
    "VentGrilleFrame",
    "VentGrilleGeometry",
    "VentGrilleMounts",
    "VentGrilleSlats",
    "VentGrilleSleeve",
    "WheelBore",
    "WheelFace",
    "WheelFlange",
    "WheelGeometry",
    "WheelHub",
    "WheelRim",
    "WheelSpokes",
    "WirePath",
    "WirePolylineGeometry",
    "boolean_difference",
    "boolean_intersection",
    "boolean_union",
    "cut_opening_on_face",
    "mesh_from_geometry",
    "save_mesh_geometry",
    "resample_side_sections",
    "rounded_rect_profile",
    "sample_arc_3d",
    "sample_catmull_rom_spline_2d",
    "sample_catmull_rom_spline_3d",
    "sample_cubic_bezier_spline_2d",
    "sample_cubic_bezier_spline_3d",
    "split_superellipse_side_loft",
    "superellipse_profile",
    "superellipse_side_loft",
    "sweep_profile_along_spline",
    "tube_from_spline_points",
    "tube_network_from_paths",
    "wire_from_points",
]

_COMPAT_MODULE = "sdk._core.v0.mesh"
for _name in __all__:
    _obj = globals().get(_name)
    if getattr(_obj, "__module__", "").startswith("sdk._core.v0._mesh"):
        with suppress(Exception):
            _obj.__module__ = _COMPAT_MODULE

del _COMPAT_MODULE, _name, _obj
