from __future__ import annotations

import sdk
from sdk._extensions.cadquery.v0 import mesh_components_from_cadquery, mesh_from_cadquery


def test_sdk_exports() -> None:
    assert hasattr(sdk, "ArticulatedObject")
    assert hasattr(sdk, "CapsuleGeometry")
    assert hasattr(sdk, "DomeGeometry")
    assert hasattr(sdk, "MeshGeometry")
    assert hasattr(sdk, "save_mesh_geometry")
    assert hasattr(sdk, "SurfaceFrame")
    assert hasattr(sdk, "SurfaceWrapMapping")
    assert hasattr(sdk, "ValidationError")
    assert hasattr(sdk, "TestContext")
    assert hasattr(sdk, "SectionLoftSpec")
    assert hasattr(sdk, "section_loft")
    assert hasattr(sdk, "repair_loft")
    assert hasattr(sdk, "ShellPartitionRegion")
    assert hasattr(sdk, "ShellPartitionSpec")
    assert hasattr(sdk, "partition_shell")
    assert hasattr(sdk, "surface_frame")
    assert hasattr(sdk, "align_centers")
    assert hasattr(sdk, "place_on_surface")
    assert hasattr(sdk, "place_on_face")
    assert hasattr(sdk, "wrap_profile_onto_surface")
    assert hasattr(sdk, "wrap_mesh_onto_surface")
    assert hasattr(sdk, "scale_geometry_to_size")
    assert hasattr(sdk, "CadQueryMeshExport")
    assert hasattr(sdk, "export_cadquery_components")
    assert hasattr(sdk, "mesh_components_from_cadquery")
    assert hasattr(sdk, "mesh_from_cadquery")
    assert hasattr(sdk, "save_cadquery_obj")
    assert hasattr(sdk, "SpurGear")
    assert hasattr(sdk, "RingGear")
    assert hasattr(sdk, "BevelGearPair")
    assert hasattr(sdk, "Worm")
    assert hasattr(sdk, "gear")
    assert hasattr(sdk, "addGear")
    assert callable(mesh_from_cadquery)
    assert callable(mesh_components_from_cadquery)
    assert not hasattr(sdk, "BufferGeometry")
    assert not hasattr(sdk, "place_on_top")
    assert not hasattr(sdk, "place_in_front_of")
    assert not hasattr(sdk, "align_centers_xy")
